# Generated by Django 5.2 on 2025-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoviesTable",
            fields=[
                ("movie_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("movie_title", models.TextField()),
            ],
            options={
                "db_table": "movies_table",
                "managed": False,
            },
        ),
    ]
