# Generated by Django 5.2 on 2025-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviestable",
            options={},
        ),
    ]
