# Generated by Django 5.2 on 2025-04-28 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0002_alter_moviestable_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviestable",
            options={"managed": False},
        ),
    ]
